name: "Check Markdown formatting"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  markdownlint:
    name: Check Markdown style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: "**/*.md"
